"""Stage 7 -- render the assignment deliverable from the Master Agent's output.

Produces output/limitations_and_research_problem.md: the bulleted list of research
gaps/limitations, followed by the paragraph-level research-problem statement.
The bullet list is generated from data/master_merged.json so that the deliverable
cannot drift from the pipeline that produced it.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import read_json, read_text, write_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "limitations" / "data"
OUT = ROOT / "limitations" / "output"

TAG = {"Author-stated": "author-stated", "Inferred": "inferred",
       "Peer-review-derived": "peer-review", "Cited": "literature-grounded"}


def main() -> int:
    merged = read_json(DATA / "master_merged.json")
    verdict = read_json(DATA / "judge_verdict_round2.json")
    manifest = read_json(DATA / "rag_manifest.json")
    retained = read_json(DATA / "rag_retained.json")

    bullets = []
    for item in sorted(merged["consolidated"], key=lambda x: x["rank"]):
        prov = ", ".join(TAG[p] for p in item["provenance"])
        bullets.append(
            f"- **[{item['id']}] {item['title']}.**\n"
            f"  {item['statement']}\n"
            f"  *Provenance: {prov}. Agent sources: {', '.join(item['sources'])}.*"
        )

    scores = " | ".join(
        f"{a} {r['total_100']:.0f}" for a, r in verdict["results"].items()
    )

    src = DATA / "research_problem.md"
    body = read_text(src) if src.exists() else ""

    doc = f"""# Limitations of DiffuLLaMA and the Continuation Research Problem

**Base paper.** Gong, Agarwal, Zhang, Ye, Zheng, Li, An, Zhao, Bi, Han, Peng, Kong.
*Scaling Diffusion Language Models via Adaptation from Autoregressive Models.* ICLR 2025.
[arXiv:2410.17891](https://arxiv.org/abs/2410.17891)

**Method.** Produced by a faithful implementation of the multi-agent framework of
Al Azher, Guo and Alhoori, *Multi-Agent LLMs for Generating Research Limitations*
([arXiv:2601.11578](https://arxiv.org/abs/2601.11578)). Four worker agents run in the
paper's sequence -- Extractor, Analyzer, Reviewer, Citation -- over the base paper's full
text and a retrieval-augmented corpus built from this project's prior literature-review
assignment (`litreview/`). A Judge Agent scores each agent on Depth, Originality,
Actionability and Topic Coverage (weights 0.2/0.2/0.3/0.3); agents scoring below 8/10 are
regenerated by the Self-Feedback Agent; a Master Agent clusters, merges and provenance-tags
the result. Methodology, deviations and honest limitations of this pipeline are in
[`REPORT.md`](../REPORT.md); every intermediate agent output is in [`data/`](../data/).

**Pipeline audit trail.** {manifest['n_chunks_total']} RAG chunks retrieved
({manifest['n_cited_in']} cited-in, {manifest['n_cited_by']} cited-by), narrowed to
{len(retained)} after re-ranking at the paper's >=8/10 threshold. 33 raw limitations from
four agents, consolidated to {len(merged['consolidated'])} after clustering and merging,
with no item dropped. Final Judge scores (of 100): {scores}.

---

## Research gaps and limitations

{chr(10).join(bullets)}

---

{body}"""
    write_text(OUT / "limitations_and_research_problem.md", doc)
    print(f"wrote {OUT/'limitations_and_research_problem.md'}")
    print(f"  bullets      : {len(bullets)}")
    print(f"  research problem section: {'present' if body else 'MISSING'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
